version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Senha123
      - MYSQL_DATABASE=Poliub

  frontend:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend/build:/usr/share/nginx/html
    depends_on:
      - backend

  mysql:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Senha123
      - MYSQL_DATABASE=Poliub
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
