services:
  backend:
    build: ./backend
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - MYSQL_URL=mysql://root:senha123@mysql:3306/poliub
      - MYSQL_HOST=localhost
      - MYSQL_USER=root
      - MYSQL_PASSWORD=senha123
      - MYSQL_DATABASE=poliub
      - ENABLE_BACKUP_SCHEDULER=true
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  mysql:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=senha123
      - MYSQL_DATABASE=poliub
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
